version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-exercise
    restart: always
    ports:
      - 27019:27017
    volumes:
      - db-data:/data/db
  exercise-tracker:
    image: exercise-tracker
    container_name: exercise-tracker
    restart: always
    depends_on:
      - mongodb
    ports:
      - 3001:3000
volumes:
  db-data:
    driver: local